### ISSUE TITLE
Improve README.md for better documentation.

### ISSUE THREAD

**Issue by ChandanShakya** [Subu19/kurasu#1]
# Hello Mister, Developer @Subu19 ;
> Please Improve the documentation i need to see what is going on.

- [ ] Close this issue after fixing the documentation.
- [ ] Also add the link to kurasu website.
- [x] Have a good day.

**Comment by Subu19** [comment]
looks fine to me :). if one has knowledge with mongodb, he/she can run it quite easily.

**Comment by ChandanShakya** [comment]
I was supposed to make comments about linking to the website.
I am not supposed to run it.
I hate mango.
Fix the documentation i.e. just improve readme.md :dancers: 
Dont be lazy like @Subu19

**Comment by Subu19** [comment]
ok sure, i will open new public repo for AnimeNepalWeb

**Comment by ChandanShakya** [comment]
It is private indeed and will contribute after last baishak ( after my semester ends)
